### TTC Bus Delays EDA

The 1st step is to download all of the data about bus delays through their API.

We first print all of the files in this package and then download them in this folder.

In [1]:
import requests

# Toronto Open Data is stored in a CKAN instance. It's APIs are documented here:
# https://docs.ckan.org/en/latest/api/

# To hit our API, you'll be making requests to:
base_url = "https://ckan0.cf.opendata.inter.prod-toronto.ca"

# Datasets are called "packages". Each package can contain many "resources"
# To retrieve the metadata for this package and its resources, use the package name in this page's URL:
url = base_url + "/api/3/action/package_show"
params = { "id": "ttc-bus-delay-data"}
package = requests.get(url, params = params).json()

# To get resource data:
for idx, resource in enumerate(package["result"]["resources"]):
    print('{idx}, {name}, {resource}'.format(idx=idx, name=resource['name'], resource=resource))
    # To get metadata for non datastore_active resources:
    if not resource["datastore_active"]:
        url = base_url + "/api/3/action/resource_show?id=" + resource["id"]
        resource_metadata = requests.get(url).json()
        print(resource_metadata)
        # From here, you can use the "url" attribute to download this file

0, ttc-bus-delay-data-readme, {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:56.253151', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': '71bb1283-7388-4d23-aa4e-0f393a80abce', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:58', 'metadata_modified': '2022-04-12T18:45:52.481023', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-readme', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 0, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 12839, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/71bb1283-7388-4d23-aa4e-0f393a80abce/download/ttc-bus-delay-data-readme.xlsx', 'url_type': 'upload'}
{'help': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/help_show?name=resource_show', 'success': True, 'result': {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:56.253151', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': '71bb1283-7388-4d23-aa4e-0f393a80abce', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:58', 'metadata_modified': '2022-04-12T18:45:52.481023', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-readme', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 0, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 12839, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/71bb1283-7388-4d23-aa4e-0f393a80abce/download/ttc-bus-delay-data-readme.xlsx', 'url_type': 'upload'}}
1, ttc-bus-delay-data-2014, {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:41.710790', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': '97b66e92-3587-4436-bd2b-bf12bc0cf683', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:58', 'metadata_modified': '2022-04-12T18:46:03.981600', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2014', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 1, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 6827210, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/97b66e92-3587-4436-bd2b-bf12bc0cf683/download/ttc-bus-delay-data-2014.xlsx', 'url_type': 'upload'}
{'help': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/help_show?name=resource_show', 'success': True, 'result': {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:41.710790', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': '97b66e92-3587-4436-bd2b-bf12bc0cf683', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:58', 'metadata_modified': '2022-04-12T18:46:03.981600', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2014', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 1, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 6827210, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/97b66e92-3587-4436-bd2b-bf12bc0cf683/download/ttc-bus-delay-data-2014.xlsx', 'url_type': 'upload'}}
2, ttc-bus-delay-data-2015, {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:44.854298', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': '8244e87c-e1fe-49d0-82d0-7facc3a07a7c', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:55', 'metadata_modified': '2022-04-12T18:46:13.798934', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2015', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 2, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 5624928, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/8244e87c-e1fe-49d0-82d0-7facc3a07a7c/download/ttc-bus-delay-data-2015.xlsx', 'url_type': 'upload'}
{'help': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/help_show?name=resource_show', 'success': True, 'result': {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:44.854298', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': '8244e87c-e1fe-49d0-82d0-7facc3a07a7c', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:55', 'metadata_modified': '2022-04-12T18:46:13.798934', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2015', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 2, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 5624928, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/8244e87c-e1fe-49d0-82d0-7facc3a07a7c/download/ttc-bus-delay-data-2015.xlsx', 'url_type': 'upload'}}
3, ttc-bus-delay-data-2016, {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:47.980087', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': 'f01fd30e-c0f0-440e-a26a-fc35c4035710', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:55', 'metadata_modified': '2022-04-12T18:46:23.897774', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2016', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 3, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 5710582, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/f01fd30e-c0f0-440e-a26a-fc35c4035710/download/ttc-bus-delay-data-2016.xlsx', 'url_type': 'upload'}
{'help': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/help_show?name=resource_show', 'success': True, 'result': {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:47.980087', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': 'f01fd30e-c0f0-440e-a26a-fc35c4035710', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:55', 'metadata_modified': '2022-04-12T18:46:23.897774', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2016', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 3, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 5710582, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/f01fd30e-c0f0-440e-a26a-fc35c4035710/download/ttc-bus-delay-data-2016.xlsx', 'url_type': 'upload'}}
4, ttc-bus-delay-data-2017, {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:52.103433', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': 'f500350d-1fe0-40da-9da7-aeeba7af1f9f', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:54', 'metadata_modified': '2022-04-12T18:46:35.678441', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2017', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 4, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 10376864, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/f500350d-1fe0-40da-9da7-aeeba7af1f9f/download/ttc-bus-delay-data-2017.xlsx', 'url_type': 'upload'}
{'help': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/help_show?name=resource_show', 'success': True, 'result': {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:52.103433', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': 'f500350d-1fe0-40da-9da7-aeeba7af1f9f', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:54', 'metadata_modified': '2022-04-12T18:46:35.678441', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2017', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 4, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 10376864, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/f500350d-1fe0-40da-9da7-aeeba7af1f9f/download/ttc-bus-delay-data-2017.xlsx', 'url_type': 'upload'}}
5, ttc-bus-delay-data-2018, {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:55.285427', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': '99c5d4de-a959-4afc-9299-3699a2c193b9', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:51', 'metadata_modified': '2022-04-12T18:46:41.921639', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2018', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 5, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 4849428, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/99c5d4de-a959-4afc-9299-3699a2c193b9/download/ttc-bus-delay-data-2018.xlsx', 'url_type': 'upload'}
{'help': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/help_show?name=resource_show', 'success': True, 'result': {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:55.285427', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': '99c5d4de-a959-4afc-9299-3699a2c193b9', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:51', 'metadata_modified': '2022-04-12T18:46:41.921639', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2018', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 5, 'resource_type': None, 'revision_id': 'e90c3e59-7576-4f54-9cb0-6d4375bcc235', 'size': 4849428, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/99c5d4de-a959-4afc-9299-3699a2c193b9/download/ttc-bus-delay-data-2018.xlsx', 'url_type': 'upload'}}
6, ttc-bus-delay-data-2019, {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:38.413861', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': 'b44b34c5-8dca-4e56-a70d-7d6666e02d3f', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:50', 'metadata_modified': '2022-04-12T18:46:49.137188', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2019', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 6, 'resource_type': None, 'revision_id': '9b23d435-dc73-4435-8bd6-83b4a609c83e', 'size': 3947457, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/b44b34c5-8dca-4e56-a70d-7d6666e02d3f/download/ttc-bus-delay-data-2019.xlsx', 'url_type': 'upload'}
{'help': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/help_show?name=resource_show', 'success': True, 'result': {'cache_last_updated': None, 'cache_url': None, 'created': '2019-07-23T18:10:38.413861', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': 'b44b34c5-8dca-4e56-a70d-7d6666e02d3f', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:50', 'metadata_modified': '2022-04-12T18:46:49.137188', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2019', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 6, 'resource_type': None, 'revision_id': '9b23d435-dc73-4435-8bd6-83b4a609c83e', 'size': 3947457, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/b44b34c5-8dca-4e56-a70d-7d6666e02d3f/download/ttc-bus-delay-data-2019.xlsx', 'url_type': 'upload'}}
7, ttc-bus-delay-data-2020, {'cache_last_updated': None, 'cache_url': None, 'created': '2020-04-28T16:59:46.887017', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': 'e5f6e6cb-2b9f-4436-aab7-283e9460bc8f', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:47', 'metadata_modified': '2022-04-12T18:46:52.881235', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2020', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 7, 'resource_type': None, 'revision_id': '7214d7c9-cd86-4c30-af28-b3fa966ec1d8', 'size': 2278860, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/e5f6e6cb-2b9f-4436-aab7-283e9460bc8f/download/ttc-bus-delay-data-2020.xlsx', 'url_type': 'upload'}
{'help': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/help_show?name=resource_show', 'success': True, 'result': {'cache_last_updated': None, 'cache_url': None, 'created': '2020-04-28T16:59:46.887017', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': 'e5f6e6cb-2b9f-4436-aab7-283e9460bc8f', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-05T19:21:47', 'metadata_modified': '2022-04-12T18:46:52.881235', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2020', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 7, 'resource_type': None, 'revision_id': '7214d7c9-cd86-4c30-af28-b3fa966ec1d8', 'size': 2278860, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/e5f6e6cb-2b9f-4436-aab7-283e9460bc8f/download/ttc-bus-delay-data-2020.xlsx', 'url_type': 'upload'}}
8, ttc-bus-delay-data-2021, {'cache_last_updated': None, 'cache_url': None, 'created': '2021-06-29T17:43:01.911475', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': '94c11eb2-1465-47a2-b321-61f1e258f5a3', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-06T14:25:32', 'metadata_modified': '2022-04-12T18:46:56.999216', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2021', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 8, 'resource_type': None, 'revision_id': '6a9d1dee-9654-43e7-96f7-0a12d47806e4', 'size': 1594308, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/94c11eb2-1465-47a2-b321-61f1e258f5a3/download/ttc-bus-delay-data-2021.xlsx', 'url_type': 'upload'}
{'help': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/help_show?name=resource_show', 'success': True, 'result': {'cache_last_updated': None, 'cache_url': None, 'created': '2021-06-29T17:43:01.911475', 'datastore_active': False, 'format': 'XLSX', 'hash': '', 'id': '94c11eb2-1465-47a2-b321-61f1e258f5a3', 'is_datastore_cache_file': False, 'is_preview': 'False', 'last_modified': '2022-04-06T14:25:32', 'metadata_modified': '2022-04-12T18:46:56.999216', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2021', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 8, 'resource_type': None, 'revision_id': '6a9d1dee-9654-43e7-96f7-0a12d47806e4', 'size': 1594308, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/94c11eb2-1465-47a2-b321-61f1e258f5a3/download/ttc-bus-delay-data-2021.xlsx', 'url_type': 'upload'}}
9, ttc-bus-delay-data-2022, {'cache_last_updated': None, 'cache_url': None, 'created': '2022-04-25T14:15:17.205082', 'datastore_active': False, 'extract_job': 'Airflow: upload_remote_files', 'format': 'XLSX', 'hash': '', 'id': '3b3c2673-5231-4aac-8b6a-dc558dce588c', 'is_preview': 'False', 'last_modified': '2023-01-23T13:56:00', 'metadata_modified': '2023-01-24T17:15:23.167278', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2022', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 9, 'resource_type': None, 'size': 843429, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/3b3c2673-5231-4aac-8b6a-dc558dce588c/download/ttc-bus-delay-data-2022.xlsx', 'url_type': 'upload'}
{'help': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/help_show?name=resource_show', 'success': True, 'result': {'cache_last_updated': None, 'cache_url': None, 'created': '2022-04-25T14:15:17.205082', 'datastore_active': False, 'extract_job': 'Airflow: upload_remote_files', 'format': 'XLSX', 'hash': '', 'id': '3b3c2673-5231-4aac-8b6a-dc558dce588c', 'is_preview': 'False', 'last_modified': '2023-01-23T13:56:00', 'metadata_modified': '2023-01-24T17:15:23.167278', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2022', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 9, 'resource_type': None, 'size': 843429, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/3b3c2673-5231-4aac-8b6a-dc558dce588c/download/ttc-bus-delay-data-2022.xlsx', 'url_type': 'upload'}}
10, ttc-bus-delay-data-2023, {'cache_last_updated': None, 'cache_url': None, 'created': '2023-02-21T21:30:09.151129', 'datastore_active': False, 'extract_job': 'Airflow: upload_remote_files', 'format': 'XLSX', 'hash': '', 'id': '10802a64-9ac0-4f2e-9538-04800a399d1e', 'is_preview': 'False', 'last_modified': '2024-01-18T21:03:11', 'metadata_modified': '2024-01-18T22:15:44.239414', 'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'mimetype_inner': None, 'name': 'ttc-bus-delay-data-2023', 'package_id': 'e271cdae-8788-4980-96ce-6a5c95bc6618', 'position': 10, 'resource_type': None, 'size': 3388271, 'state': 'active', 'url': 'https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/e271cdae-8788-4980-96ce-6a5c95bc6618/resource/10802a64-9ac0-4f2e-9538-04800a399d1e/download/ttc-bus-delay-data-2023.xlsx', 'url_type': 'upload'}

In [2]:
for idx, resource in enumerate(package["result"]["resources"]):
    xlsx_url = resource["url"]
    response = requests.get(xlsx_url)
    
    if response.status_code == 200:
        # Assuming you want to save the XLSX content to a file
        xlsx_filename = f"{resource['name']}.xlsx"
        with open(xlsx_filename, "wb") as file:
            file.write(response.content)
        print(f"XLSX resource downloaded successfully. Check '{xlsx_filename}' file.")
    else:
        print("Failed to download the XLSX resource.")
        break  # Exit the loop if there was an error

XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-readme.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2014.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2015.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2016.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2017.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2018.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2019.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2020.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2021.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2022.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2023.xlsx' file.
XLSX resource downloaded successfully. Check 'ttc-bus-delay-data-2024.xlsx' file.

### Importing packages for EDA

In [3]:
import pandas as pd
import numpy as np

In [4]:
#sometimes it's more convenient to look at DFs with these settings
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

### Readme

In [5]:
df_readme = pd.read_excel('ttc-bus-delay-data-readme.xlsx')
df_readme

,Field Name,Description,Example
0,Report Date,The date (YYYY/MM/DD) when the delay-causing incident occurred,2017-06-20 00:00:00
1,Route,The number of the bus route,51
2,Time,The time (hh:mm:ss AM/PM) when the delay-causing incident occurred,00:35:00
3,Day,The name of the day,Monday
4,Location,The location of the delay-causing incident,York Mills Station
5,Incident,The description of the delay-causing incident,Mechanical
6,Min Delay,"The delay, in minutes, to the schedule for the following bus",10
7,Min Gap,"The total scheduled time, in minutes, from the bus ahead of the following bus",20
8,Direction,"The direction of the bus route where B,b or BW indicates both ways. (On an east west route, it includes both east and west) NB - northbound, SB - southbound, EB - eastbound, WB - westbound",N
9,Vehicle,Vehicle number,1057

In [6]:
df = pd.read_excel('ttc-bus-delay-data-2022.xlsx')
df.head(20)

,Date,Route,Time,Day,Location,Incident,Min Delay,Min Gap,Direction,Vehicle
0,2022-01-01,320,02:00,Saturday,YONGE AND DUNDAS,General Delay,0,0,NaN,8531
1,2022-01-01,325,02:00,Saturday,OVERLEA AND THORCLIFFE,Diversion,131,161,W,8658
2,2022-01-01,320,02:00,Saturday,YONGE AND STEELES,Operations - Operator,17,20,S,0
3,2022-01-01,320,02:07,Saturday,YONGE AND STEELES,Operations - Operator,4,11,S,0
4,2022-01-01,320,02:13,Saturday,YONGE AND STEELES,Operations - Operator,4,8,S,0
5,2022-01-01,363,02:16,Saturday,KING AND SHAW,Operations - Operator,30,60,NaN,0
6,2022-01-01,96,02:18,Saturday,HUMBERLINE LOOP,Security,0,0,N,3536
7,2022-01-01,320,02:38,Saturday,STEELES AND YONGE,Operations - Operator,4,8,NaN,0
8,2022-01-01,320,02:55,Saturday,YONGE AND STEELES,Operations - Operator,4,8,NaN,0
9,2022-01-01,300,03:18,Saturday,KENNEDY STATION,Emergency Services,0,0,E,8094
10,2022-01-01,300,03:32,Saturday,BLOOR AND INDIAN,Security,17,34,E,8452
11,2022-01-01,47,03:34,Saturday,LANSDOWNE AND ST CLAIR,Operations - Operator,15,30,S,0
12,2022-01-01,45,03:52,Saturday,DANFORTH AND DANFORTH,Operations - Operator,30,60,W,1325
13,2022-01-01,32,04:21,Saturday,EGLINTON STATION,Operations - Operator,16,33,NaN,1130
14,2022-01-01,32,04:39,Saturday,YONGE AND BERWICK,Emergency Services,0,0,S,1267
15,2022-01-01,39,04:42,Saturday,FINCHDENE AND FINCH,Operations - Operator,30,60,W,0
16,2022-01-01,32,04:53,Saturday,RENFORTH STATION,Operations - Operator,30,0,E,1073
17,2022-01-01,53,04:58,Saturday,STEELES AND BAYVIEW,Security,30,60,E,3299
18,2022-01-01,29,05:01,Saturday,DUFFERIN AND LAWRENCE,Operations - Operator,10,20,NaN,9149
19,2022-01-01,334,05:02,Saturday,FINCHDENE AND FINCH,Operations - Operator,33,0,W,8744

In [7]:
df.tail(20)

,Date,Route,Time,Day,Location,Incident,Min Delay,Min Gap,Direction,Vehicle
58687,2022-12-31,121,20:41,Saturday,FRONT AND BAY,Operations - Operator,20,40,E,8455
58688,2022-12-31,36,20:53,Saturday,FINCH AND WESTON,Operations - Operator,11,22,E,8906
58689,2022-12-31,100,21:23,Saturday,WYNFORD AND DONMILS,Mechanical,9,18,S,8820
58690,2022-12-31,20,21:30,Saturday,KENNEDY STATION,Cleaning - Unsanitary,20,40,W,8551
58691,2022-12-31,20,21:32,Saturday,DANFORTH AND MIDLAND,Cleaning - Unsanitary,20,40,S,8551
58692,2022-12-31,7,21:40,Saturday,BATHURST AND WILSON,Operations - Operator,9,18,N,8360
58693,2022-12-31,36,21:45,Saturday,FINCH AND MARTIN GROVE,Diversion,0,0,W,0
58694,2022-12-31,53,21:45,Saturday,FINCH STATION,Cleaning - Unsanitary,19,39,W,3226
58695,2022-12-31,169,21:48,Saturday,SCARBOROUGH CENTRE STA,Cleaning - Unsanitary,30,30,N,3151
58696,2022-12-31,927,21:50,Saturday,FINCH AND MARTIN GROVE,Diversion,64,75,W,0
58697,2022-12-31,7,22:06,Saturday,BATHURST AND GREENWIN,Utilized Off Route,9,18,S,8340
58698,2022-12-31,47,22:13,Saturday,YORKDALE STATION,Operations - Operator,20,40,S,8184
58699,2022-12-31,63,22:51,Saturday,OSSINGTON STATION,General Delay,10,20,N,8376
58700,2022-12-31,72,23:12,Saturday,QUEENS QUAY AND BAY,Diversion,292,308,E,0
58701,2022-12-31,68,23:16,Saturday,ANGUS GLEN COMMUNITY C,Cleaning - Unsanitary,33,66,S,9229
58702,2022-12-31,32,23:21,Saturday,EGLINTON AND EDITH (W,Mechanical,2,24,W,1085
58703,2022-12-31,113,23:28,Saturday,DANFORTH AND DAWES,Vision,20,40,W,8589
58704,2022-12-31,72,23:56,Saturday,LOWER SHERBOURNE AND L,Security,18,36,N,8493
58705,2022-12-31,22,00:17,Saturday,BINGHAM LOOP,Cleaning - Unsanitary,10,20,S,8582
58706,2022-12-31,7,00:28,Saturday,BATHURST STATION,General Delay,10,20,N,8354

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58707 entries, 0 to 58706
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       58707 non-null  datetime64[ns]
 1   Route      58323 non-null  object
 2   Time       58707 non-null  object
 3   Day        58707 non-null  object
 4   Location   58707 non-null  object
 5   Incident   58707 non-null  object
 6   Min Delay  58707 non-null  int64
 7   Min Gap    58707 non-null  int64
 8   Direction  48227 non-null  object
 9   Vehicle    58707 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 4.5+ MB

In [9]:
df.describe()

                                Date     Min Delay       Min Gap       Vehicle
count                          58707  58707.000000  58707.000000  58707.000000
mean   2022-07-03 11:48:01.066993664     20.115353     32.676154   5467.459298
min              2022-01-01 00:00:00      0.000000      0.000000      0.000000
25%              2022-04-06 00:00:00      9.000000     17.000000   1553.000000
50%              2022-07-13 00:00:00     11.000000     22.000000   7959.000000
75%              2022-09-27 00:00:00     20.000000     36.000000   8546.000000
max              2022-12-31 00:00:00    999.000000    999.000000  93561.000000
std                              NaN     48.945121     50.636856   4356.685772

### Notes
1. Delays are substantial - the median is 11 minutes
2. The mean of the delays is way higher than the median, which indicates a lot of outliers which skew the distribution (for example, you already can see from df.tail(20) 292 minutes delay)
3. Lots of missing values in direction - not a problem for us, it's not an important column, so we can just drop it
4. A bit of missing values in route, we can drop these rows if anything or drop the column too
5. The most important columns IMO are date, time, day, location, incident, and min delay

### Next steps
1. To find out how many delays are under 0 or 5 minutes
2. To print all of the incident values and get additional explanation for them if needed
3. To compare all other years of data (to understand if it's the same format)

In [10]:
df[df['Min Delay'] == 0].info()

<class 'pandas.core.frame.DataFrame'>
Index: 2818 entries, 0 to 58693
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2818 non-null   datetime64[ns]
 1   Route      2585 non-null   object
 2   Time       2818 non-null   object
 3   Day        2818 non-null   object
 4   Location   2818 non-null   object
 5   Incident   2818 non-null   object
 6   Min Delay  2818 non-null   int64
 7   Min Gap    2818 non-null   int64
 8   Direction  1604 non-null   object
 9   Vehicle    2818 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 242.2+ KB

In [11]:
df[df['Min Delay'] <= 5].info()

<class 'pandas.core.frame.DataFrame'>
Index: 5602 entries, 0 to 58702
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       5602 non-null   datetime64[ns]
 1   Route      5348 non-null   object
 2   Time       5602 non-null   object
 3   Day        5602 non-null   object
 4   Location   5602 non-null   object
 5   Incident   5602 non-null   object
 6   Min Delay  5602 non-null   int64
 7   Min Gap    5602 non-null   int64
 8   Direction  3868 non-null   object
 9   Vehicle    5602 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 481.4+ KB

Not so many short delays. Maybe we can just drop the rows below a certain threshold (5 minutes, 10 minutes?). It's basically how we define a significant delay

In [12]:
df['Incident'].value_counts()

Incident
Operations - Operator               19583
Mechanical                          16469
Collision - TTC                      3512
Security                             3374
Utilized Off Route                   3240
General Delay                        3218
Diversion                            2883
Emergency Services                   2421
Cleaning - Unsanitary                1561
Investigation                         906
Vision                                708
Road Blocked - NON-TTC Collision      624
Held By                               162
Late Entering Service                  40
Cleaning - Disinfection                 6
Name: count, dtype: int64

The main reason is an operator incident. If we try to predict this with weather, we can leave only the most sensitive to weather reasons (like Mechanical, Diversion, Collision TTC, Emergency Services, etc.)

In [13]:
df['Min Delay'].value_counts().sort_index()

Min Delay
0      2818
1       121
2        62
3       223
4       603
5      1775
6      1799
7      2589
8      3970
9      4568
10     9453
11     2384
12     2910
13     1682
14     1448
15     2951
16     1262
17     1298
18     1391
19      487
20     3896
21      424
22      786
23      675
24     1017
25      842
26      341
27      214
28      186
29       89
30     3001
31       58
32      115
33      102
34       53
35       81
36       75
37       36
38       54
39       39
40      165
41       22
42       33
43       16
44       37
45       66
46       41
47       24
48       23
49       28
50       74
51       16
52       23
53       22
54       23
55       35
56       16
57       23
58       11
59       16
60      171
61       20
62       24
63       23
64       11
65       21
66       17
67       14
68       23
69       14
70       37
71        8
72       15
73        8
74       16
75       22
76       12
77        5
78       14
79        5
80       27
81        6
82       12
83        8
84       15
85       20
86       13
87        9
88        8
89       13
90       39
91        9
92        7
93        9
94       10
95       10
96       10
97       11
98        5
99       11
100      16
101      13
102      17
103       9
104       9
105      21
106       7
107       9
108      27
109       8
110      14
111       3
112      10
113       5
114      25
115      13
116      11
117      14
118       8
119      10
120      52
121      11
122      12
123       8
124       7
125      12
126       8
127       6
128       5
129       4
130      12
131       1
132       9
133       5
134       2
135       6
136       5
137       9
138       8
139       4
140      15
141       4
142       7
143       7
144      11
145      11
146       7
147       7
148       5
149       3
150      12
151       8
152       6
153       6
154       4
155       6
156       4
157       7
158       2
159       5
160      12
161       5
162      11
163       2
164       2
165       6
166       1
167       6
168       6
169       1
170       4
171       4
172       1
173       5
174       2
175       5
176       2
177       2
178       5
179       2
180      17
181       1
182       3
183       5
184       3
185       3
186       3
187       6
189       5
190       5
191       4
192       2
193       1
194       7
195       4
196       2
197       4
198       2
199       3
200       7
201       1
202       2
204       2
205       5
206       2
207       4
208       1
209       1
210       8
211       3
212       3
213       3
215       6
216       4
218       3
219       1
220       5
221       1
223       2
224       1
225       5
226       6
227       3
228       1
229       1
230       1
232       4
233       1
234       3
235       4
236       1
237       8
238       3
239       2
240      19
241       2
242       1
243       3
244       1
245       3
246       2
247       3
248       4
249       2
250       7
253       4
254       2
255       2
256       1
257       3
259       2
260       3
261       2
262       8
263       2
265       3
266       1
267       5
268       3
269       3
270       6
271       2
272       3
273       2
274       2
275       4
278       3
280       5
283       2
284       3
285       3
287       1
288       1
289       2
290       3
291       1
292       1
293       4
294       2
295       3
296       2
297       1
298       1
299       1
300       9
301       1
302       2
303       1
304       4
305       4
306       1
307       5
310       4
311       1
312       2
313       1
314       1
315       1
317       1
318       2
319       1
320       3
321       1
323       3
325       3
329       1
330       4
333       2
334       3
335       2
336       1
337       5
338       1
340       1
341       1
342       1
343       3
345       5
348       1
349       2
350       1
351       2
352       1
355       2
357       2
358       1
359       2
360      14
361       2
362       2
363       1
365       1
366       1
368       2
369       1
372       3
373       1
375       6
376       1
377       1
382       5
383       1
384       1
385       1
386       1
390       2
391       1
393       3
394       1
395       1
400       3
402       1
403       2
405       2
406       2
410       2
411       5
413       1
417       2
420       9
423       1
424       1
425       3
426       1
427       3
428       1
430       1
432       2
433       1
434       2
437       1
441       2
442       1
444       2
450       1
452       1
453       2
454       1
455       1
456       3
457       1
459       1
460       2
462       1
463       1
469       1
471       2
472       2
475       2
478       1
480       7
483       1
487       2
489       1
490       2
491       1
493       2
497       1
499       2
500       2
502       1
504       2
508       1
510       2
513       1
517       1
525       1
526       1
530       1
531       1
532       1
533       1
536       1
538       2
540       5
543       1
548       1
558       1
560       1
583       1
586       1
590       1
596       2
597       2
598       1
600       3
602       1
611       1
617       1
622       1
625       1
628       1
630       2
635       1
636       1
637       1
643       1
647       1
648       1
654       1
656       2
657       1
659       2
660       3
661       1
670       1
672       1
678       1
681       1
682       2
685       1
690       2
698       1
708       1
711       3
715       1
717       2
720       7
730       1
734       2
735       1
738       1
746       2
748       1
752       1
758       1
761       1
765       1
767       1
773       1
780       2
791       1
794       1
800       1
807       2
830       1
840       2
842       1
844       1
856       1
858       1
864       1
869       2
872       1
877       1
878       1
881       1
890       1
895       1
900       3
901       1
907       1
909       1
923       1
931       1
938       2
947       1
949       2
960       1
964       1
970       2
983       1
987       1
994       2
999       4
Name: count, dtype: int64

### Comparing all of the files

First we will look at .info(), then at .describe()

In [15]:
years = np.arange(2014, 2025, 1)
for year in years:
    df = pd.read_excel('ttc-bus-delay-data-{}.xlsx'.format(year))
    print(df.info())
    print('\n')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9822 entries, 0 to 9821
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Report Date  9822 non-null   datetime64[ns]
 1   Route        9822 non-null   int64
 2   Time         9822 non-null   object
 3   Day          9822 non-null   object
 4   Location     9814 non-null   object
 5   Incident     9822 non-null   object
 6   Min Delay    9819 non-null   float64
 7   Min Gap      9819 non-null   float64
 8   Direction    9734 non-null   object
 9   Vehicle      8641 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 767.5+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6665 entries, 0 to 6664
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Report Date  6665 non-null   datetime64[ns]
 1   Route        6665 non-null   int64
 2   Time         6665 non-null   object
 3   Day          6665 non-null   object
 4   Location     6659 non-null   object
 5   Incident     6665 non-null   object
 6   Min Delay    6665 non-null   int64
 7   Min Gap      6664 non-null   float64
 8   Direction    6451 non-null   object
 9   Vehicle      6237 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 520.8+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5326 entries, 0 to 5325
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Report Date  5326 non-null   datetime64[ns]
 1   Route        5326 non-null   int64
 2   Time         5326 non-null   object
 3   Day          5326 non-null   object
 4   Location     5321 non-null   object
 5   Incident     5326 non-null   object
 6   Min Delay    5326 non-null   int64
 7   Min Gap      5323 non-null   float64
 8   Direction    5226 non-null   object
 9   Vehicle      4884 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 416.2+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5300 entries, 0 to 5299
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Report Date  5300 non-null   datetime64[ns]
 1   Route        5300 non-null   int64
 2   Time         5300 non-null   object
 3   Day          5300 non-null   object
 4   Location     5293 non-null   object
 5   Incident     5300 non-null   object
 6   Min Delay    5298 non-null   float64
 7   Min Gap      5299 non-null   float64
 8   Direction    5193 non-null   object
 9   Vehicle      4963 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 414.2+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6969 entries, 0 to 6968
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Report Date  6969 non-null   datetime64[ns]
 1   Route        6969 non-null   int64
 2   Time         6969 non-null   object
 3   Day          6969 non-null   object
 4   Location     6956 non-null   object
 5   Incident     6969 non-null   object
 6   Min Delay    6968 non-null   float64
 7   Min Gap      6968 non-null   float64
 8   Direction    6746 non-null   object
 9   Vehicle      6027 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 544.6+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6743 entries, 0 to 6742
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Report Date  6743 non-null   datetime64[ns]
 1   Route        6743 non-null   int64
 2   Time         6743 non-null   object
 3   Day          6743 non-null   object
 4   Location     6711 non-null   object
 5   Incident     6743 non-null   object
 6   Min Delay    6715 non-null   float64
 7   Min Gap      6687 non-null   float64
 8   Direction    6612 non-null   object
 9   Vehicle      5515 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 526.9+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4282 entries, 0 to 4281
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Report Date  4282 non-null   datetime64[ns]
 1   Route        4282 non-null   int64
 2   Time         4282 non-null   object
 3   Day          4282 non-null   object
 4   Location     4277 non-null   object
 5   Incident     4282 non-null   object
 6   Delay        4272 non-null   float64
 7   Gap          4270 non-null   float64
 8   Direction    4179 non-null   object
 9   Vehicle      3858 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 334.7+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2832 entries, 0 to 2831
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2832 non-null   datetime64[ns]
 1   Route      2832 non-null   int64
 2   Time       2832 non-null   object
 3   Day        2832 non-null   object
 4   Location   2832 non-null   object
 5   Incident   2832 non-null   object
 6   Min Delay  2832 non-null   int64
 7   Min Gap    2832 non-null   int64
 8   Direction  2503 non-null   object
 9   Vehicle    2832 non-null   int64
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 221.4+ KB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58707 entries, 0 to 58706
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       58707 non-null  datetime64[ns]
 1   Route      58323 non-null  object
 2   Time       58707 non-null  object
 3   Day        58707 non-null  object
 4   Location   58707 non-null  object
 5   Incident   58707 non-null  object
 6   Min Delay  58707 non-null  int64
 7   Min Gap    58707 non-null  int64
 8   Direction  48227 non-null  object
 9   Vehicle    58707 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 4.5+ MB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56207 entries, 0 to 56206
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       56207 non-null  datetime64[ns]
 1   Route      55637 non-null  object
 2   Time       56207 non-null  object
 3   Day        56207 non-null  object
 4   Location   56207 non-null  object
 5   Incident   56207 non-null  object
 6   Min Delay  56207 non-null  int64
 7   Min Gap    56207 non-null  int64
 8   Direction  46667 non-null  object
 9   Vehicle    56207 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 4.3+ MB
None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4764 entries, 0 to 4763
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4764 non-null   datetime64[ns]
 1   Route      4712 non-null   float64
 2   Time       4764 non-null   object
 3   Day        4764 non-null   object
 4   Location   4764 non-null   object
 5   Incident   4764 non-null   object
 6   Min Delay  4764 non-null   int64
 7   Min Gap    4764 non-null   int64
 8   Direction  3995 non-null   object
 9   Vehicle    4764 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(5)
memory usage: 372.3+ KB
None

In [17]:
for year in years:
    df = pd.read_excel('ttc-bus-delay-data-{}.xlsx'.format(year))
    print(year, len(df)) #number of delays per year

2014 9822
2015 6665
2016 5326
2017 5300
2018 6969
2019 6743
2020 4282
2021 2832
2022 58707
2023 56207
2024 4764

In [18]:
for year in years:
    df = pd.read_excel('ttc-bus-delay-data-{}.xlsx'.format(year))
    print(df.describe())
    print('\n')

                         Report Date        Route    Min Delay      Min Gap  \
count                           9822  9822.000000  9819.000000  9819.000000
mean   2014-01-16 01:20:29.321930240    86.089188    12.651288    21.837560
min              2014-01-01 00:00:00     1.000000    -1.000000     0.000000
25%              2014-01-07 00:00:00    36.000000     6.000000    10.000000
50%              2014-01-16 00:00:00    60.000000     9.000000    17.000000
75%              2014-01-24 00:00:00   105.000000    14.000000    26.000000
max              2014-01-31 00:00:00   909.000000  1160.000000   730.000000
std                              NaN    89.551231    27.901961    29.568837

           Vehicle
count  8641.000000
mean   5402.250434
min       0.000000
25%    1554.000000
50%    7401.000000
75%    7932.000000
max    9965.000000
std    3184.568138


                         Report Date        Route    Min Delay      Min Gap  \
count                           6665  6665.000000  6665.000000  6664.000000
mean   2015-01-16 07:50:33.938484736   104.297674    12.623706    21.597389
min              2015-01-01 00:00:00     1.000000     0.000000     0.000000
25%              2015-01-08 00:00:00    39.000000     5.000000    10.000000
50%              2015-01-16 00:00:00    73.000000     9.000000    18.000000
75%              2015-01-24 00:00:00   116.000000    14.000000    26.000000
max              2015-01-31 00:00:00   999.000000  1244.000000  1254.000000
std                              NaN   125.709890    31.097107    28.124225

           Vehicle
count  6237.000000
mean   5487.781946
min       0.000000
25%    1549.000000
50%    7514.000000
75%    8119.000000
max    9449.000000
std    3293.934639


                         Report Date        Route    Min Delay      Min Gap  \
count                           5326  5326.000000  5326.000000  5323.000000
mean   2016-01-15 15:40:53.623732736    99.663913    13.914758    23.723464
min              2016-01-01 00:00:00     1.000000     0.000000     0.000000
25%              2016-01-09 00:00:00    39.000000     6.000000    11.000000
50%              2016-01-15 00:00:00    68.000000    10.000000    20.000000
75%              2016-01-22 00:00:00   110.000000    15.000000    28.000000
max              2016-01-31 00:00:00   999.000000   702.000000   732.000000
std                              NaN   120.139262    28.044764    32.276436

           Vehicle
count  4884.000000
mean   5630.089271
min       0.000000
25%    1641.000000
50%    7603.000000
75%    8142.250000
max    9999.000000
std    3215.912300


                         Report Date        Route    Min Delay      Min Gap  \
count                           5300  5300.000000  5298.000000  5299.000000
mean   2017-01-15 16:32:30.792452864    96.798868    14.532465    24.895641
min              2017-01-01 00:00:00     1.000000     0.000000     0.000000
25%              2017-01-09 00:00:00    36.750000     7.000000    12.000000
50%              2017-01-15 00:00:00    72.000000    10.000000    20.000000
75%              2017-01-24 00:00:00   113.000000    15.000000    29.000000
max              2017-01-31 00:00:00   810.000000   865.000000   885.000000
std                              NaN   109.334415    32.571708    35.008609

           Vehicle
count  4963.000000
mean   5679.603264
min       0.000000
25%    1611.000000
50%    7686.000000
75%    8159.000000
max    9335.000000
std    3247.407898


                         Report Date        Route    Min Delay      Min Gap  \
count                           6969  6969.000000  6968.000000  6968.000000
mean   2018-01-15 11:26:25.363753728   101.238485    15.704363    25.708094
min              2018-01-01 00:00:00     2.000000   -30.000000     0.000000
25%              2018-01-08 00:00:00    37.000000     6.000000    12.000000
50%              2018-01-15 00:00:00    71.000000    10.000000    20.000000
75%              2018-01-24 00:00:00   112.000000    15.000000    28.000000
max              2018-01-31 00:00:00   807.000000  1158.000000  1158.000000
std                              NaN   122.002932    51.587622    52.791892

           Vehicle
count  6027.000000
mean   5762.609922
min       1.000000
25%    1594.000000
50%    7883.000000
75%    8514.000000
max    9152.000000
std    3392.389631


                         Report Date        Route    Min Delay      Min Gap  \
count                           6743  6743.000000  6715.000000  6687.000000
mean   2019-01-20 01:12:10.891294464   200.670621    18.111690    28.644534
min              2019-01-01 00:00:00     1.000000   -10.000000     0.000000
25%              2019-01-13 00:00:00    39.000000     7.000000    13.000000
50%              2019-01-22 00:00:00    79.000000    10.000000    20.000000
75%              2019-01-28 00:00:00   129.000000    17.000000    30.000000
max              2019-01-31 00:00:00   995.000000   999.000000   999.000000
std                              NaN   298.098413    48.876234    53.136688

           Vehicle
count  5515.000000
mean   5731.875793
min       0.000000
25%    1639.500000
50%    8090.000000
75%    8699.000000
max    9558.000000
std    3400.965386


                         Report Date        Route        Delay          Gap  \
count                           4282  4282.000000  4272.000000  4270.000000
mean   2020-01-16 21:33:42.793087232   213.951425    18.806414    29.410773
min              2020-01-01 00:00:00     1.000000     0.000000     0.000000
25%              2020-01-10 00:00:00    40.000000     7.000000    14.000000
50%              2020-01-17 00:00:00    75.000000    10.000000    20.000000
75%              2020-01-24 00:00:00   133.750000    16.000000    30.000000
max              2020-01-31 00:00:00   999.000000   999.000000   999.000000
std                              NaN   315.138537    60.375278    61.936690

           Vehicle
count  3858.000000
mean   5504.896319
min       0.000000
25%    3143.250000
50%    7920.500000
75%    8655.500000
max    9315.000000
std    3217.990704


                                Date        Route    Min Delay      Min Gap  \
count                           2832  2832.000000  2832.000000  2832.000000
mean   2021-01-16 03:38:38.644067840   143.686794    22.357345    34.786723
min              2021-01-01 00:00:00     1.000000     0.000000     0.000000
25%              2021-01-08 00:00:00    36.000000     9.000000    18.000000
50%              2021-01-16 00:00:00    65.000000    12.000000    24.000000
75%              2021-01-24 00:00:00   116.000000    20.000000    40.000000
max              2021-01-31 00:00:00   999.000000   970.000000   930.000000
std                              NaN   238.790408    64.225133    56.715677

            Vehicle
count   2832.000000
mean    5424.228814
min        0.000000
25%     3167.250000
50%     3643.000000
75%     8531.000000
max    80888.000000
std     3965.182203


                                Date     Min Delay       Min Gap       Vehicle
count                          58707  58707.000000  58707.000000  58707.000000
mean   2022-07-03 11:48:01.066993664     20.115353     32.676154   5467.459298
min              2022-01-01 00:00:00      0.000000      0.000000      0.000000
25%              2022-04-06 00:00:00      9.000000     17.000000   1553.000000
50%              2022-07-13 00:00:00     11.000000     22.000000   7959.000000
75%              2022-09-27 00:00:00     20.000000     36.000000   8546.000000
max              2022-12-31 00:00:00    999.000000    999.000000  93561.000000
std                              NaN     48.945121     50.636856   4356.685772


                                Date     Min Delay       Min Gap       Vehicle
count                          56207  56207.000000  56207.000000  56207.000000
mean   2023-07-13 15:27:51.870051840     20.251606     32.897557   5576.547370
min              2023-01-01 00:00:00      0.000000      0.000000      0.000000
25%              2023-04-15 00:00:00      9.000000     17.000000   3155.000000
50%              2023-07-23 00:00:00     11.000000     21.000000   7270.000000
75%              2023-10-12 00:00:00     20.000000     40.000000   8545.000000
max              2023-12-31 00:00:00    998.000000    992.000000  91024.000000
std                              NaN     50.170167     52.287433   3741.874633


                                Date        Route    Min Delay      Min Gap  \
count                           4764  4712.000000  4764.000000  4764.000000
mean   2024-01-15 16:02:25.088161280   216.079160    21.645886    34.534005
min              2024-01-01 00:00:00     1.000000     0.000000     0.000000
25%              2024-01-08 00:00:00    40.000000     9.000000    18.000000
50%              2024-01-16 00:00:00    82.000000    11.000000    22.000000
75%              2024-01-23 00:00:00   131.000000    20.000000    40.000000
max              2024-01-31 00:00:00   999.000000   950.000000   949.000000
std                              NaN   317.836408    51.898619    53.762929

            Vehicle
count   4764.000000
mean    5886.914568
min        0.000000
25%     3245.750000
50%     7255.000000
75%     8540.000000
max    88101.000000
std     4279.253598

It's weird that the size of dfs range from 3000 to 50000. One of the explanations - covid. Duration of delays increased over the years, but not extremely

In [19]:
for year in years:
    df = pd.read_excel('ttc-bus-delay-data-{}.xlsx'.format(year))
    print(year, df['Incident'].value_counts())
    print('\n')

2014 Incident
Mechanical             5401
Utilized Off Route     1356
Late Leaving Garage    1148
General Delay          1010
Investigation           536
Diversion               267
Emergency Services      104
Name: count, dtype: int64


2015 Incident
Mechanical             2961
Late Leaving Garage    1325
Utilized Off Route     1074
Investigation           480
General Delay           475
Diversion               247
Emergency Services      103
Name: count, dtype: int64


2016 Incident
Mechanical             2342
Late Leaving Garage     864
Utilized Off Route      845
Investigation           486
General Delay           445
Diversion               257
Emergency Services       87
Name: count, dtype: int64


2017 Incident
Mechanical             2164
Late Leaving Garage    1007
Utilized Off Route      975
Investigation           499
General Delay           287
Diversion               262
Emergency Services      106
Name: count, dtype: int64


2018 Incident
Mechanical             2246
Late Leaving Garage    1397
Utilized Off Route     1359
General Delay           860
Investigation           655
Diversion               323
Emergency Services      129
Name: count, dtype: int64


2019 Incident
Mechanical             2130
Late Leaving Garage    1291
General Delay          1202
Utilized Off Route      893
Investigation           705
Diversion               371
Emergency Services      151
Name: count, dtype: int64


2020 Incident
Mechanical                          1657
Investigation                        637
Utilized Off Route                   582
General Delay                        326
Late Leaving Garage - Mechanical     303
Diversion                            276
Late Leaving Garage - Operator       150
Vision                               146
Emergency Services                   109
Late Leaving Garage - Management      62
Late Leaving Garage - Vision          34
Name: count, dtype: int64


2021 Incident
Mechanical                          890
Cleaning                            808
Operations - Operator               218
Security                            211
Collision - TTC                     182
Emergency Services                  150
Road Blocked - NON-TTC Collision    120
Investigation                        94
General Delay                        73
Vision                               51
Utilized Off Route                   24
Held By                               3
Late Leaving Garage - Operator        2
Management                            2
Late Leaving Garage - Operations      2
Late Leaving Garage - Mechanical      1
Diversion                             1
Name: count, dtype: int64


2022 Incident
Operations - Operator               19583
Mechanical                          16469
Collision - TTC                      3512
Security                             3374
Utilized Off Route                   3240
General Delay                        3218
Diversion                            2883
Emergency Services                   2421
Cleaning - Unsanitary                1561
Investigation                         906
Vision                                708
Road Blocked - NON-TTC Collision      624
Held By                               162
Late Entering Service                  40
Cleaning - Disinfection                 6
Name: count, dtype: int64


2023 Incident
Mechanical                          19235
Operations - Operator               11360
Security                             4807
Collision - TTC                      3909
Diversion                            3805
General Delay                        3199
Emergency Services                   3017
Utilized Off Route                   2363
Cleaning - Unsanitary                2152
Investigation                        1247
Vision                                787
Road Blocked - NON-TTC Collision      249
Held By                                77
Name: count, dtype: int64


2024 Incident
Mechanical                          1789
Operations - Operator                844
Security                             374
Diversion                            367
Collision - TTC                      332
General Delay                        259
Emergency Services                   233
Utilized Off Route                   210
Cleaning - Unsanitary                164
Vision                               101
Investigation                         81
Road Blocked - NON-TTC Collision      10
Name: count, dtype: int64

Operations - Operator category appeared only in 2021. Still the difference in observations per year is just too big. Good for discussion - why the numbers of observations differ so much from year to year?